#!/usr/bin/env sh
# Pre-commit hook - run lint-staged
# Note: This hook is called from the root hook which already changes to this directory
# Use the shell script wrapper directly via sh to avoid CRLF/npx issues
sh node_modules/.bin/lint-staged
