#!/bin/bash
# Deploy script for: Stateful Backend, Messaging, Core Applications, Scheduling App, News Ingestion Job
# This script was generated by the EnginEdge Control Center.
set -e

kubectl cluster-info >/dev/null 2>&1 || { echo 'Cluster offline'; exit 1; }

echo 'Starting Kubernetes deployment...'

# --- Applying Secrets and ConfigMaps ---
kubectl apply -f C:\Users\chris\Engineering\EnginEdge\enginedge-core\platform\k8s\config/core-config.yaml
kubectl apply -f C:\Users\chris\Engineering\EnginEdge\enginedge-core\platform\k8s\config/news-ingestion-config.yaml
kubectl apply -f C:\Users\chris\Engineering\EnginEdge\enginedge-core\platform\k8s\config/scheduling-model-config.yaml
kubectl apply -f C:\Users\chris\Engineering\EnginEdge\enginedge-core\platform\k8s\config/worker-config.yaml
kubectl apply -f C:\Users\chris\Engineering\EnginEdge\enginedge-core\platform\k8s\secrets/minio-secret.yaml
kubectl apply -f C:\Users\chris\Engineering\EnginEdge\enginedge-core\platform\k8s\secrets/postgres-secret.yaml

# --- Installing Helm Charts for 3rd party services ---
helm repo add bitnami https://charts.bitnami.com/bitnami
helm repo add minio https://charts.min.io/
helm repo update

helm install kafka bitnami/kafka -f C:\Users\chris\Engineering\EnginEdge\enginedge-core\platform\k8s\charts/kafka/values.yaml --namespace default
helm install minio minio/minio -f C:\Users\chris\Engineering\EnginEdge\enginedge-core\platform\k8s\charts/minio/values.yaml --namespace default
helm install postgres-metastore bitnami/postgresql -f C:\Users\chris\Engineering\EnginEdge\enginedge-core\platform\k8s\charts/postgres/values.yaml --namespace default
helm install redis bitnami/redis -f C:\Users\chris\Engineering\EnginEdge\enginedge-core\platform\k8s\charts/redis/values.yaml --namespace default

# --- Deploying Core Applications ---
kubectl apply -f C:\Users\chris\Engineering\EnginEdge\enginedge-core\platform\k8s\apps/agent-tool-worker.yaml
kubectl apply -f C:\Users\chris\Engineering\EnginEdge\enginedge-core\platform\k8s\apps/control-plane.yaml
kubectl apply -f C:\Users\chris\Engineering\EnginEdge\enginedge-core\platform\k8s\apps/main-node.yaml
kubectl apply -f C:\Users\chris\Engineering\EnginEdge\enginedge-core\platform\k8s\apps/data-processing-worker.yaml
kubectl apply -f C:\Users\chris\Engineering\EnginEdge\enginedge-core\platform\k8s\apps/interview-worker.yaml
kubectl apply -f C:\Users\chris\Engineering\EnginEdge\enginedge-core\platform\k8s\apps/latex-worker.yaml
kubectl apply -f C:\Users\chris\Engineering\EnginEdge\enginedge-core\platform\k8s\apps/llm-worker.yaml
kubectl apply -f C:\Users\chris\Engineering\EnginEdge\enginedge-core\platform\k8s\apps/news-ingestion-cronjob.yaml
kubectl apply -f C:\Users\chris\Engineering\EnginEdge\enginedge-core\platform\k8s\apps/resume-worker.yaml
kubectl apply -f C:\Users\chris\Engineering\EnginEdge\enginedge-core\platform\k8s\apps/scheduling-model.yaml
kubectl apply -f C:\Users\chris\Engineering\EnginEdge\enginedge-core\platform\k8s\apps/wolfram-kernel.yaml

echo 'Kubernetes deployment finished.'
