#!/bin/bash
# Deploy script for: Stateful Backend, Messaging, Core Applications, Scheduling App, News Ingestion Job
# This script was generated by the EnginEdge Control Center.
set -e

kubectl cluster-info >/dev/null 2>&1 || { echo 'Cluster offline'; exit 1; }

echo 'Starting Kubernetes deployment...'

# --- Applying Secrets and ConfigMaps ---
kubectl apply -f ../k8s/config/main-node-config.yaml
kubectl apply -f ../k8s/config/news-ingestion-config.yaml
kubectl apply -f ../k8s/config/scheduling-model-config.yaml
kubectl apply -f ../k8s/config/worker-node-config.yaml
kubectl apply -f ../k8s/secrets/minio-secret.yaml
kubectl apply -f ../k8s/secrets/postgres-secret.yaml

# --- Installing Helm Charts for 3rd party services ---
helm repo add bitnami https://charts.bitnami.com/bitnami
helm repo add minio https://charts.min.io/
helm repo update

helm upgrade --install kafka bitnami/kafka -f ../k8s/charts/kafka/values.yaml --namespace default
helm upgrade --install minio minio/minio -f ../k8s/charts/minio/values.yaml --namespace default
helm upgrade --install postgres-metastore bitnami/postgresql -f ../k8s/charts/postgres/values.yaml --namespace default
helm upgrade --install redis bitnami/redis -f ../k8s/charts/redis/values.yaml --namespace default

# --- Deploying Core Applications ---
kubectl apply -f ../k8s/apps/main-node.yaml
kubectl apply -f ../k8s/apps/news-ingestion-cronjob.yaml
kubectl apply -f ../k8s/apps/scheduling-model.yaml
kubectl apply -f ../k8s/apps/wolfram-kernel.yaml
kubectl apply -f ../k8s/apps/worker-node.yaml

echo 'Kubernetes deployment finished.'
