#!/bin/bash
# Deploy script for: Messaging
# This script was generated by the EnginEdge Control Center.
set -e

kubectl cluster-info >/dev/null 2>&1 || { echo 'Cluster offline'; exit 1; }

echo 'Starting Kubernetes deployment...'

# --- Installing Helm Charts for 3rd party services ---
helm repo add bitnami https://charts.bitnami.com/bitnami
helm repo add minio https://charts.min.io/
helm repo update

helm upgrade --install kafka bitnami/kafka -f ../k8s/charts/kafka/values.yaml --namespace default
helm upgrade --install redis bitnami/redis -f ../k8s/charts/redis/values.yaml --namespace default

echo 'Kubernetes deployment finished.'
